### PR TITLE
added dark theme

### PR DESCRIPTION
**Pull request by utkarsh4321**
Hii I worked on a dark theme issue.
issue-#1

Please review my work and tell me if there is any problem I will try to fix it asap.
Thank you

### CODE REVIEW

**Comment by utkarsh4321** [comment]
Please review it and tell me if there is any problem

**Comment by akarshansonkar** [comment]
Okay sure I’ll review it i need some time because of my busy schedule so
try to understand.

**Comment by utkarsh4321** [comment]
No problem take your time but please review it and tell me before hacktoberfest close.

**Comment by akarshansonkar** [comment]
Yaa sure just give me two days

**Comment by utkarsh4321** [comment]
@akarshansonkar Hii did you get a chance to check it?

**Comment by akarshansonkar** [comment]
Not yet I’ll surely do it by tomorrow. Sorry for the delay

**Comment by akarshansonkar** [comment]
hey @utkarsh4321 can you mail me the preview of the dark theme which you have added ? it's because i am not able to see the preview

**Comment by utkarsh4321** [comment]
can i send you screenshot of it

**Comment by akarshansonkar** [comment]
Yes please

**Comment by utkarsh4321** [comment]
mailed you please check that

**Comment by akarshansonkar** [comment]
Nice Work man!!

**Pull request merged**
